### ISSUE TITLE
Does not ping search engines for multiple domains

### ISSUE THREAD

**Issue by aredondo** [kjvarga/sitemap_generator#164]
I have got a configuration similar to this:

```
SitemapGenerator::Sitemap.default_host = 'http://www.host1.com'
SitemapGenerator::Sitemap.create(:sitemaps_path => 'sitemap-1/') do
  add '/page1', :priority => 0.9, :changefreq => 'daily'
end

SitemapGenerator::Sitemap.default_host = 'http://www.host2.com'
SitemapGenerator::Sitemap.create(:sitemaps_path => 'sitemap-2/') do
  add '/page2', :priority => 0.9, :changefreq => 'daily'
end
```

The issue I am finding is that when I run `rake sitemap:refresh`, sitemap_generator only pings the search engines for the last domain:

```
$ bundle exec rake sitemap:refresh
In '/home/app/Site/public/':
+ sitemap-1/sitemap.xml.gz                                2 links /  363 Bytes
Sitemap stats: 2 links / 1 sitemaps / 0m00s
In '/home/app/Site/public/':
+ sitemap-2/sitemap.xml.gz                                2 links /  357 Bytes
Sitemap stats: 2 links / 1 sitemaps / 0m00s

Pinging with URL 'http://www.host2/sitemap-en/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing
```

Since the generation of sitemaps and pinging the search engines run as unrelated tasks, the latter only knows about the last configuration of `SitemapGenerator::Sitemap`.

As a work-around, I will make a script that uses sitemap_generator instead of relying on the Rake tasks.

Thanks.

**Comment by frnco** [comment]
Wouldn't it be better to ping at the end of `create`?

For instance, calling the ping method (Unless `no_ping` was specificed obviously) right after

          output(sitemap_index.stats_summary(:time_taken => end_time - start_time)) if verbose

would work as expected for everyone.

**Comment by kjvarga** [comment]
How would you pass the `no_ping` flag down from the Rake task to the create method, so it knows not to ping in that case?

**Comment by frnco** [comment]
Well, most likely I would accept a `ping` or `no_ping` param or something for the `sitemap:create` Rake Task, and pass it from the `sitemap:refresh:no_ping` version.

This also may have the added benefit of making it easier if you find the need to have other option(s), especially if it comes in as an options hash.

I didn't test it, but I imagined something like this:

For the create:

    task :create => ['sitemap:require_environment'], :ping do |t, args|
      no_ping = true if args[:ping] == :no_ping
      no_ping ||= false
      SitemapGenerator::Interpreter.run(:config_file => ENV["CONFIG_FILE"], :verbose => verbose, :no_ping => no_ping)
    end

Thus the new `refresh:no_ping` would become something like:

    task 'refresh:no_ping' => ["sitemap:create[#{args[:no_ping]}]"]

And people could also call it using:

    rake sitemap:refresh[:no_ping]


Or `sitemap:refres[:ping => false]` or whatever you end up deciding on, I think you get the idea. :D

Maybe you would prefer to use an ENV Variable. That's your call obviously (As it is your call to decide if you even want to implement it).

This is somewhat of an edge case, and the current solution works fine, perhaps just documenting the need to ping manually would be more than enough, especially if you conclude this will add unnecessary complexity, since this is more of an "added benefit from some refactoring" than an actual bug.
