### ISSUE TITLE
Parallel group processing

### ISSUE THREAD

**Issue by mikeverbeck** [kjvarga/sitemap_generator#191]
I am trying decrease the time it takes to generate a sitemap.  My thought is to process groups using the [parallel gem](https://github.com/grosser/parallel).  I was thinking I could create group objects in threads then use the result to build a sitemap object.  Unfortunately I am having trouble generating group objects and then associating them to the sitemap object.  Is it even possible to assemble the sitemap without using blocks?  
Here is the gist of what I am attempting.  This code doesn't work at all but it's the thought process.
```
$sm = SitemapGenerator::Sitemap.create()

group1 = lambda {
  $sm.group(:filename => :group1, :sitemaps_path => 'sitemaps/group1') do
    add '/forum/needmorepaths'
  end
}

group2 = lambda {
  $sm.group(:filename => :group2, sitemaps_path => 'sitemaps/group2') do
    add '/store/morepaths'
  end
}

Parallel.each([group1, group2]){|job| job.call()}
#maybe do some $sm.sitemap building with group1 and group2 results here.
```

**Comment by mikeverbeck** [comment]
So I got this working but the code doesn't seem ideal.  Someone with more experience manipulating groups can probably do it more cleanly. We saw a nice performance gain by using multiple processes.  Our 2M url generation previously took about ~5hrs.  Now it takes 74 minutes.

````
SitemapGenerator::Sitemap.create(:compress => false, :create_index => false) do
  group1 = lambda {
    group = sitemap.group(:filename => :group1, :sitemaps_path => 'sitemaps/group1') do
      Record.find_each do |record|
        add '/record/path'
      end
    end
    group.sitemap.write unless group.sitemap.written?  #write if not full
  }

  # group2 like above...

  Parallel.each([group1, group2], :in_processes => 8) do |group|
    group.call
  end
end

#regenerate the index sitemap xml file because I couldn't figure out how to track it with multiple processes
SitemapGenerator::Sitemap.create(:compress => false) do
  Dir.chdir(sitemap.public_path.to_s)
  xml_files      = File.join("**", "sitemaps", "**", "*.xml")
  xml_file_paths = Dir.glob(xml_files)

  xml_file_paths.each do |file|
    add file
  end
end
````

**Comment by lfv89** [comment]
@mikeverbeck Did you ever manage NOT TO generate the "default" sitemap.xml.gz? (the one generated by the gem before your regenerate it by yourself).

**Comment by mikeverbeck** [comment]
@lfv89  Not that I recall. It's been a year since I worked on the code and I no longer have access to it (changed jobs).  The default sitemap.xml.gz had no problems generating previously.  It just took a very long time due to the size of the site.

**Comment by kjvarga** [comment]
I'm very surprised it would take 5 hours (!!!) to generate just 2M links.  The bottleneck there must be your database.  Regardless, here's some info that might help you as this issue is coming up more regularly now (i.e. breaking up sitemap generation using workers, parallel jobs).

First off `SitemapGenerator::Sitemap` is a shared instance of the `LinkSet` class provided to create a simple interface.  So if your code is running in a shared memory environment they will be sharing the same LinkSet which unless you know what you're doing could give unexpected results.  It could mean that you can have the sitemap index built for you if you avoid finalizing the sitemaps until all the groups have finished generating.

Yes, everything can be done without using blocks.  If you don't pass a block to `group` it will return the "group" (really a LinkSet instance which shares the sitemap index instance of the LinkSet it was created from).

You shouldn't be using `sitemap.group`, just `group`.  Because you're passing a block to your `group` call the file will be written out at the end of the block, so you shouldn't need to call `sitemap.write`.

You should be able to do something like the following:

```ruby
sitemap = SitemapGenerator::LinkSet.new
sitemap.compress = false
sitemap.sitemaps_host = 'http://threadedgoodies.com'
groups = []
groups << lambda {
  puts "executing group1"
  sitemap.group(:filename => :group1) do
    add '/group1-path'
  end
}
groups << lambda {
  puts "executing group2"
  sitemap.group(:filename => :group2) do
    add '/group2-path'
  end
}
groups << lambda {
  puts "executing group3"
  sitemap.group(:filename => :group3) do
    add '/group3-path'
  end
}

Parallel.each(groups, :in_threads => 8) do |group|
  group.call
end

# This has to be called after all the groups have been processed.  Don't know how
# to do that with the parallel gem
sitemap.finalize_sitemap_index!  # write out the index file
```

This is a threaded example.   If you're using processes you can't share the same instance, and you'll have to manually build your index file similarly to how you did it above.  But it looks like you're adding full file paths to the index when you should only be adding a portion of the path.  Also, better to use `add_to_index` method rather than `add` to add links to the index file only.

**Comment by kjvarga** [comment]
Actually there are problems with that example.  Strangely the groups aren't all written out every time.  And there's some threading issue (surprise) that leads to odd results.  Here's a simpler example of multiple processes:

```ruby
groups = []
options = { :sitemaps_host => 'http://threadedgoodies.com', :compress => false }
groups << lambda {
  SitemapGenerator::Sitemap.group(options.merge(:filename => :group1)) do
    add '/group1-path'
  end.sitemap.write
}
groups << lambda {
  SitemapGenerator::Sitemap.group(options.merge(:filename => :group2)) do
    add '/group2-path'
  end.sitemap.write
}
groups << lambda {
  SitemapGenerator::Sitemap.group(options.merge(:filename => :group3)) do
    add '/group3-path'
  end.sitemap.write
}

Parallel.each(groups, :in_processes => 8, &:call)
```

**Comment by mikeverbeck** [comment]
@kjvarga I believe you are right, we had to query the database for portions of the url.

Thanks for sharing the code.  I'll pass it along to the guys who are currently maintaining it.
