### ISSUE TITLE
Is there any issue has been occurred while uploading to s3 carrierwave?

### ISSUE THREAD

**Issue by sanyam-j** [kjvarga/sitemap_generator#204]
Hi i am using the gem from past 1 month and its working properly and uploading the sitemap to s3. But today as i run it again, it creating to site map to local directory. Is there any issue?

**Comment by kjvarga** [comment]
Hey.  You're using the WaveAdapter then I presume?  No changes were made to that in the latest release.  The sitemaps have always been written to the local filesystem, perhaps you didn't notice before?  Or has the location changed?  It writes them to disk and then uploads those files to S3. 

The change that was made in the latest release was to the S3Adapter.  Instead of `require 'fog'` we `require 'fog/storage'` so only the fog-aws gem is required and not the whole fog gem.

**Comment by sanyam-j** [comment]
Yes i am use the Wave Adapter. OK thanks for the update.
