### ISSUE TITLE
Sitemap Generation Issues in Worker Queues

### ISSUE THREAD

**Issue by ehoch** [kjvarga/sitemap_generator#206]
Not sure if anyone else is crazy enough to run these Sitemaps inside worker queues (Resque, Sidekiq, etc), but I currently put  

```
SitemapGenerator::Interpreter.run(:config_file => config_file)
```

Inside a .perform method. The issue is if you run two of them in a row, it seems to be grabbing the naming settings of the previous sitemap. So for example if I have:

```
SitemapGenerator::Sitemap.create({include_root: false, filename: :video_sitemap }) do
...
end
```
And then run
```
SitemapGenerator::Sitemap.create({include_root: false, filename: :image_sitemap }) do
...
end
```
The second sitmeap will end up with the video_sitemap1.xml.gz inside its index file. I'm not sure if I'm being clear enough but basically if you end up with two index files that both run inside the same Rails instance (because I'm not using rake tasks) it's using the names from the first index file in the subsequent ones.

Maybe there's some memoization or something going on? Or please let me know what I'm doing wrong. I've tried to debug but things get a big complicated with the index file generation..

**Comment by kjvarga** [comment]
Hmm, looking at the code, that should work because `create()` resets the index and other instance variables before the sitemap generation.  Maybe I'm missing something obvious.  

Until I get to dig deeper, you can try creating a new LinkSet instance (which is what `SitemapGenerator::Sitemap` is and setting your config and options on that).  That will ensure you have a new object and sitemap each time. e.g.

```ruby
sitemap = SitemapGenerator::LinkSet.new
sitemap.default_host = '...'
sitemap.create({include_root: false, filename: :image_sitemap }) do
...
end
```

What you are doing (using Runners) should be entirely possible and I'm not sure why it's not working as intended.  There's obviously a shared object somewhere that I'm clearing in the `LinkSet#reset!` method.
