### ISSUE TITLE
VERBOSE not working

### ISSUE THREAD

**Issue by ifightcrime** [kjvarga/sitemap_generator#209]
Passing verbose in during the create task is causing `VERBOSE` not to work for me. I'm on rake 10.4.0, and sitemap_generator 5.1.0.

https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/tasks.rb#L51

`verbose` comes from `Rake::FileUtilsExt`, where the default value is `Object`:

https://github.com/ruby/rake/blob/f3f06cdcc84a46945d14730791fffceb6d6b305b/lib/rake/file_utils_ext.rb#L16

I think what's happening is it's overriding the value I pass in using `VERBOSE=false` with `Object`. This seems to occur while pass in the env variable, as well as explicitly setting `SitemapGenerator.verbose = false`. I wasn't having this problem before I started using groups, so not sure if that's related.

My workaround right now is to just override the default sitemap task and not pass verbose in:

```ruby
require 'sitemap_generator'

Rake::Task['sitemap:create'].clear

namespace :sitemap do
  desc "Generate sitemaps but don't ping search engines.  Alias for refresh:no_ping."
  task :create => ['sitemap:require_environment'] do
    SitemapGenerator::Interpreter.run(:config_file => ENV["CONFIG_FILE"])
  end
end
```

If that looks good I can send a pull request. Wasn't 100% sure if passing that in was intended or not, or if you have a better fix.

**Comment by kjvarga** [comment]
Wow, Rake is retarded.  They've changed the handling a few times.  And now no matter the value of VERBOSE (true/false) it is set to an Object?  That's dumb.  I've updated the README to only support the `-s` option: https://github.com/kjvarga/sitemap_generator#preventing-output

VERBOSE=false/true still works when calling as a script rather than a rake task.  But using -s and --verbose will work for Rake.  If you have set `SitemapGenerator.verbose` then that will always take precedence.

**Comment by ifightcrime** [comment]
:+1:  thanks!
