### ISSUE TITLE
Is the CarrierWave documentation deprecated?

### ISSUE THREAD

**Issue by tiagoovieira** [kjvarga/sitemap_generator#260]
If I'm not mistaken the aws new endpoint is `http://bucket.s3.awsamazon.com/`

my sitemap.rb file is as following
```
SitemapGenerator::Sitemap.default_host = my_domain
SitemapGenerator::Sitemap.sitemaps_host = "http://#{ENV["bucket_name"]}.s3.amazonaws.com/"
SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/"
SitemapGenerator::Sitemap.adapter = SitemapGenerator::WaveAdapter.new
SitemapGenerator::Sitemap.create do
 ... add routes
end
```

It's creating locally, but not in S3 bucket.

**Comment by tiagoovieira** [comment]
Well, used Fog config instead, it seems to work

**Comment by zwallacedev** [comment]
@tiagoovieira Were you able to get this to create it in S3 w/o using Fog? We have CarrierWave setup to use the :aws config for other areas of our project, and I don't want to change it for everything.

**Comment by zwallacedev** [comment]
@tiagoovieira I am having the same issue, where the sitemap is generated locally in my path, but it is not being pushed to S3.

**Comment by kjvarga** [comment]
Unfortunately I'm not actively using this configuration myself.  CarrierWave has terrible (no) debugging support that I'm aware of, so it's difficult to pinpoint where the issue lies.  Perhaps they've enabled some debugging more recently?  I'd take a look at that.  It certainly _can_ work, and worked in the past.

**Comment by zwallacedev** [comment]
@kjvarga I appreciate the response, and your gem is 🔥. It turns out that this was actually an error on my side, and not on your configuration. Once I get this hooked up, I'll let you know. Also, I appreciate your work on this gem, and if you need any help, I would love to submit a PR in an effort to keep this gem alive.

**Comment by kjvarga** [comment]
Thanks for the offer @zwallacedev.  I'm not actively developing on it anymore, just maintaining it, so it would be good to have someone who is active and has some time to dedicate to keeping it current.
