### ISSUE TITLE
Generate sitemap in parallel with Sidekiq jobs

### ISSUE THREAD

**Issue by phlegx** [kjvarga/sitemap_generator#275]
Hi!

I want to create a sitemap in parallel with Sidekiq. My plan is to write a rake task that starts the Sidekiq jobs. But I have some problems to get all to work.

**Here an example code:**

```ruby
# SitemapJob gets called many times with a set of objects. 
class SitemapJob < ActiveJob::Base

  def perform(objects)
    SitemapGenerator::Interpreter.send :include, ActionView::Helpers
    SitemapGenerator::Interpreter.send :include, Rails.application.routes.url_helpers
    SitemapGenerator::Interpreter.send :include, MyProject::Sitemap

    sitemap = SitemapGenerator::LinkSet.new
    sitemap.sitemaps_path = 'sitemaps/'
    sitemap.default_host = 'http://example.com'
    sitemap.create_index = false
    sitemap.compress = true
    
    # Do some process here. Get data from database 
    # and call method from MyProject::Sitemap to add the link to the sitemap.
    # e.g. my_special_add
    sitemap.create do
      objects.each { |obj| my_special_add(obj, sitemap) }
    end

  end
end
```

**Here my questions**

1. How can I use groups?
3. How can I add a link?
2. How can I create the index file manually after all jobs are finished?

**Comment by kjvarga** [comment]
I've been meaning to add more docs around this usage example.  Well done for using a new instance of LinkSet for each job.

First off you don't need `SitemapGenerator::Interpreter.send :include, Rails.application.routes.url_helpers` because those are already included in Interpreter.  The other other includes should work, I don't see why they wouldn't.  `sitemap.create` lazy-instantiates an Interpreter instance and the block passed to `create` is then eval'ed within the interpreter instance.

1.  You can use groups as per usual in your `create` block, e.g. 
  ```ruby
    sitemap.create do
      group(:filename => :mygroupname) do
        add('/url')
      end
    end
  ```
2. Add links using `add` as per usual.  I'm not sure what your `my_special_add` method is doing, but if it's included in the Interpreter it should have access to the `add` method.  Alternatively you can just call `add` on the `sitemap` instance that you pass in to `my_special_add ` like so: `sitemap.add('/url')`.  The interpreter is just a proxy for those methods anyways.

3.  There is an example in one of the closed issues where someone shows how they enumerate the files in their sitemaps folder and add them to the index file manually to generate the index file.  Use the `add_to_index` method from in the block or `sitemap.add_to_index` to add a URL to the index file.  You'll generate the index after generating all the sitemaps, so it'll be a separate job I expect.

**Comment by phlegx** [comment]
Thank you @kjvarga! I will publish here a complete example later. This can help other people to generate sitemaps in parallel.

**Comment by phlegx** [comment]
# SOLUTION (Rails Project)

1. Create rake tasks

```ruby
# lib/tasks/sitemap.rake

namespace :sitemap do
  # rake sitemap:create
  desc 'Create sitemap'
  task :create => :environment do |task|
    puts 'Starting creating sitemap...'
    puts "- Max sitemap files: #{SitemapGenerator::MAX_SITEMAP_FILES}"
    puts "- Max sitemap filesize: #{SitemapGenerator::MAX_SITEMAP_FILESIZE}"
    puts "- Max sitemap links: #{SitemapGenerator::MAX_SITEMAP_LINKS}"
    
    # Get some data from database or what you need to add links
    # Sidekiq job accepts only strings, numbers, arrays or hashes as parameters
    objects = [{ id: 1, name: 'Test1', path: '/hello-test' }, {...}]
    group = 'posts' # Example for a group
    SitemapJob.perform_later(objects, group)

    puts
    puts 'ATTENTION: Don\'t forget to collect all sitemaps in one sitemap file!'
    puts 'Please run \'bundle exec rake sitemap:build\' after all sitemap jobs has finished.'
  end

  # rake sitemap:build
  desc 'Build sitemap'
  task :build => :environment do |task|
    puts 'Starting building main sitemap...'
    SitemapGenerator.verbose = Rails.env.development?
    SitemapGenerator::Sitemap.sitemaps_path = 'sitemap/'
    SitemapGenerator::Sitemap.default_host = 'http://example.com'
    SitemapGenerator::Sitemap.create(compress: false, include_root: false) do
      xml_files = File.join(sitemap.public_path, sitemap.sitemaps_path, '**', Rails.env.development? ? '*.xml' : '*.xml.gz')
      Dir.glob(xml_files).each do |file|
        add_to_index(file)
      end
    end
  end
end

```

2. Create `SitemapJob`

```ruby
# app/jobs/sitemap_job.rb

class SitemapJob < ActiveJob::Base
  queue_as :default

  def perform(objects, group)
    SitemapGenerator.verbose = Rails.env.development?
    sitemap = SitemapGenerator::LinkSet.new
    sitemap.sitemaps_path = 'sitemap/'
    sitemap.default_host = 'http://example.com'
    sitemap.create_index = false
    sitemap.compress = !Rails.env.development?

    sitemap.create do
      group(sitemaps_path: "sitemap/#{group}/", filename: group, compress: !Rails.env.development?) do
        objects.each do |obj|
          add(obj[:path])
        end
      end
    end
  end

end

```

3. Run first rake task to create all sitemaps.

`bundle exec rake sitemap:create`

4. After all jobs has finished run rake task to bundle all sitemaps to one index file.

`bundle exec rake sitemap:bundle`

**Comment by lfv89** [comment]
Thanks @phlegx and @kjvarga.
