### ISSUE TITLE
X-Robots-Tag for the sitemap

### ISSUE THREAD

**Issue by karensg** [kjvarga/sitemap_generator#284]
I would like to add the X-Robots-Tag to my sitemap in order to remove it from the Google Search results and I am using the AwsSdkAdapter.
Is it possible to add a headers functionality to the gem so we can set headers such as this one?

More info: 
https://webmasters.stackexchange.com/questions/62978/prevent-xml-sitemaps-from-showing-up-in-google-search-results

**Comment by kjvarga** [comment]
Because `X-Robots-Tag` is a response header, it is independent of the sitemap file, and is not under my control.  You will have to configure your file server to include this header when you serve the sitemap file to the requestor.  Unfortunately S3 does not appear to support this header: https://stackoverflow.com/questions/25790047/setting-noindex-on-amazon-s3-objects
