### ISSUE TITLE
Use Version 3 of aws-sdk 

### ISSUE THREAD

**Issue by bitsapien** [kjvarga/sitemap_generator#289]
Version 3 of Aws SDK has split the gem libraries based on the service. Since `sitemap_generator`'s AwsSdkAdapter concerns only the S3 service. Use `aws-sdk-s3` instead of `aws-sdk`.

**Comment by bodrovis** [comment]
This is the line we are talking about https://github.com/kjvarga/sitemap_generator/blob/bd26778ee866ac5848ee07e98c85958b53b036d8/lib/sitemap_generator/adapters/aws_sdk_adapter.rb#L2. This is how the issue was resolved in another gem https://github.com/janko-m/shrine/blob/master/lib/shrine/storage/s3.rb#L2

**Comment by kjvarga** [comment]
I've release v6 of the gem.  In this version, the user must `require` whichever library they like, rather than leave that up to the SitemapGenerator gem to do.

See https://github.com/kjvarga/sitemap_generator#supported-adapters

**Comment by bitsapien** [comment]
Thanks 👍

**Comment by januszm** [comment]
Just a note, if you still use the v2 of the aws-sdk, then do not add `require 'aws-sdk'`, you probably have the `aws-sdk-resources` gem already loaded.
