### ISSUE TITLE
google cros-site submissions

### ISSUE THREAD

**Issue by ThomasSertorio** [kjvarga/sitemap_generator#330]
Related to https://github.com/kjvarga/sitemap_generator/issues/98 but could not get it working.

- The website is hosted on Heroku and he sitemap successfully generated and hosted on a S3 bucket.
- In the google search console, I have successfully verify the website `https://www.telescope.co.com` and the sitemap `https://telescope-sitemaps.s3.eu-west-3.amazonaws.com/sitemaps` and uploaded the sitemap for this propriety

Yet when I check the the sitemap tap of the website propriety (`https://www.telescope.co.com`) no sitemap are found and I can't fill in a sitemap url with a different host.

Am I missing something in https://github.com/kjvarga/sitemap_generator#an-example-of-using-an-adapter

**Comment by jrochkind** [comment]
Is the Sitemap there on your S3 bucket? Sounds like yes, since you ay you succesfully verified the sitemap. 

I don't believe this has anything to do with this gem (which is succesfully generating the sitemap). Rather, it's a just a bit tricky working with sitemaps on different hosts than the site indexed. Google's admin UI tools may not work with them. (Not sure what you mean by 

 this will have nothing to do with this gem -- rather it can be tricky to get Google to accept a sitemap on a different host than the site indexed, and it may not work with standard Google admin tools. (Not sure what you mean by "I check the the sitemap tap of the website propriety", but it sounds like you are using googles admin web UI). 

Try googling for "sitemap on different domain" or "cross-domain sitemap". I don't believe it is related to this gem's production of the sitemap.

**Comment by ThomasSertorio** [comment]
You're right the gem is successfully generating the sitemap, there's no issue there.

But in the meantime, the gem generates sitemaps which intend to be uploaded on Google Admin 99% of time. As there's already a section in the doc with an example of remotely hosted sitemap and a reference to google webmaster tools (https://github.com/kjvarga/sitemap_generator#an-example-of-using-an-adapter), I felt it was the place to ask and at the end the doc would benefit from the answer.

**Comment by kjvarga** [comment]
Sorry I can't provide support for connection issues.
