### ISSUE TITLE
[sorbet] Include libraries for static type checking

### ISSUE THREAD

**Issue by artagnon** [kjvarga/sitemap_generator#339]
```
$ bundle exec srb init
```

fails in a project with `sitemap_generator`, because there are undefined classes; to resolve the issue, I had to install the gems `fog-aws`, `aws-sdk`, and `carrierwave`. Moreover, there are plenty of errors from sorbet. Any clues on what can be done to improve the situation?

**Comment by kjvarga** [comment]
The upload adapters have conditionals that ensure that the classes they depend on, which are provided by other gems, are present, e.g.

```ruby
if !defined?(::CarrierWave::Uploader::Base)
  raise "Error: `CarrierWave::Uploader::Base` is not defined.\n\n"\
        "Please `require 'carrierwave'` - or another library that defines this class."
end
```

When you say that it "fails in a project with sitemap_generator", do you mean that you have sitemap_generator installed as a gem via the Gemfile in your project and that that still causes issues with Sorbet?  So sorbet also traverses each gem?  That would be unusual.

I don't see an easy solution.  What Sorbet is doing by requiring every file is not always going to work.  The best I can think of is for you to define shims which define the missing classes and ensure that that file is required before the sitemap generator processing.  Otherwise you will introduce dependencies to your project that you don't need.

It might also be possible to skip the defined check in some circumstances but that feels a bit hacky.  Thoughts?

**Comment by artagnon** [comment]
Yes, sorbet traverses each gem.

I played around a bit with sorbet, and decided that it has plenty of other shortcomings; it's not worth the trouble, and I'm closing this issue. Thanks.

**Comment by feliperaul** [comment]
@artagnon I'm also trying out sorbet and stuck on sitemap_genertor raising this exception.

I'm curious, however, on what other shortcomings you have discovered in your exploration. Would you care to elaborate?
