### ISSUE TITLE
Exception when using Sorbet: `Fog::Storage` is not defined

### ISSUE THREAD

**Issue by feliperaul** [kjvarga/sitemap_generator#345]
Sorbet (https://sorbet.org/) is a great ruby type checker (and LSP server, with autocompletion, goto definition, and so son).

I'm trying to install it on my project, but it fails initialization in sitemap_generator gem:

```
sitemap_generator-6.0.1/lib/sitemap_generator/adapters/s3_adapter.rb:2:in `<top (required)>': Error: `Fog::Storage` is not defined. (RuntimeError)
```

Is there any chance this can be patched?

**Comment by kjvarga** [comment]
Sitemap generator provides adapters which work with some common gems, but
in order to keep the coupling as loose as possible it does not require the
gems itself - the user is required to do that.  So there are some usages of
classes which are not defined until runtime.  Maybe there’s a way to define
some exceptions so that Sorbet will ignore these missing classes?

**Comment by feliperaul** [comment]
@kjvarga I couldn't find any way to do that. Unfortunately this is the only gem that's causing this exception (if I comment it out in our gemfile, Sorbet can work just fine).

Let me know if you have any ideas on how to avoid this. I'll keep investigating as well.
