### ISSUE TITLE
Pretty format 

### ISSUE THREAD

**Issue by dharshann** [kjvarga/sitemap_generator#350]
When successfully ran, it creates a output file which simply has a huge xml line. Can this be pretty formatted? Along with this.

- Does sitemap.xml needs pretty formatting? 
- Any specific styling guidelines for formatting sitemap.xml?

**Comment by kjvarga** [comment]
There is no need to format sitemaps for human readability, because they are consumed by machines, and the added whitespace characters needlessly increase the size of your files.  

Since the sitemap is just XML there are probably hundreds of tools for viewing pretty formatted and interactive versions of it.  The easiest is to open the `.xml` file in your web browser.

Alternatively there are online tools: https://www.google.com/search?q=format+xml&oq=format+xml&aqs=chrome..69i57j0l7.2409j0j7&sourceid=chrome&ie=UTF-8

**Comment by kjvarga** [comment]
On *nix you can use `xmllint --format <file>`

**Comment by dharshann** [comment]
Thanks @kjvarga

**Comment by andyw8** [comment]
+1  for this feature request. I'm making changes to the code which generates my sitemap, and I want to diff the old and new versions. I can convert each individually then compare, but it would be convenient to have a `pretty` option.
