### ISSUE TITLE
TypeError: no implicit conversion of Integer into String

### ISSUE THREAD

**Issue by MiroBabic** [kjvarga/sitemap_generator#358]
I have in my sitemap config specific url build for ids of model like this which worked for long time
```
Procurer.connection.execute("select id from procurers").each do |proc|
    literal "/my_special_url/"+proc["id"], :priority => 1, :change_frequency => "daily"
  end
```
I havent noticed when this stopped working but now when I run rake sitemap:generate I get issue with implicit conversion of integer into string.
What is the actual way to generate custom urls in sitemap?

**Comment by kjvarga** [comment]
I expect that you upgraded Ruby at some point because this is a Ruby error, not related to SitemapGenerator.  Take a look at https://stackoverflow.com/questions/56530904/ruby-code-error-no-implicit-conversion-of-integer-into-string

There are examples in the README of how to use Rails URL helpers to generate your URLs.  But if you're not using Rails, then your approach is fine.

**Comment by MiroBabic** [comment]
you're right, I didnt notice that that call returns integers as IDs (looks like before I updated ruby it returned strings) so I just modified it like this

```
Procurer.connection.execute("select id from procurers").each do |proc|
    literal "/my_special_url/"+(proc["id"].to_s), :priority => 1, :change_frequency => "daily"
  end

```

thanks
