### ISSUE TITLE
Memory increases but does not decrease after running `sitemap:refresh`

### ISSUE THREAD

**Issue by thanhtoan1196** [kjvarga/sitemap_generator#364]
Memory increases but does not decrease after running `sitemap:refresh`

**Comment by kjvarga** [comment]
If you're running via Rake task then the memory must be freed once the rake process exists.  When sitemaps are written their [XML content is cleared](https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/builder/sitemap_file.rb#L140)

**Comment by thanhtoan1196** [comment]
@kjvarga but I use with sidekiq job, memery sidekiq doesn't drop after it is done

**Comment by kjvarga** [comment]
I see.  I'm not sure what could be holding onto memory, since the file data should be cleared after being written.  Maybe you're assigning links/records to an instance variable that isn't being cleared?  

`SitemapGenerator::Sitemap` is a "singleton" proxy for a `LinkSet` instance which hold information about the sitemap generated.  You could try to delete the old `LinkSet` instance after generating your sitemaps by calling `SitemapGenerator::Sitemap.reset!` https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator.rb#L50

Maybe you can share your config to see if anything could be cached there?

**Comment by thanhtoan1196** [comment]
this is my config
```ruby
SitemapGenerator::Sitemap.default_host = "http://www.example.com"
SitemapGenerator::Sitemap.sitemaps_host = "http://www.example.com"
SitemapGenerator::Sitemap.sitemaps_path = 'build/sitemaps/ngontinh'
# SitemapGenerator::Sitemap.max_sitemap_links = 40000
SitemapGenerator::Sitemap.compress = false
SitemapGenerator::Sitemap.create do

  add "/", :changefreq => 'yearly', :priority => 1.0

  Book.publish.select(:id, :slug, :updated_at, :created_at).find_each do |book|
    add "/book/#{book.slug}", :changefreq => 'yearly', :lastmod => book.updated_at, :priority => 1.0
  end
end
# SitemapGenerator::Sitemap.ping_search_engines

```

**Comment by kjvarga** [comment]
Your config looks good.  Did `SitemapGenerator::Sitemap.reset!` after generating your sitemap work?

**Comment by thanhtoan1196** [comment]
Thanks, it's fine now
