### ISSUE TITLE
Is there a way to get sitemap.xml contents into Ruby string?

### ISSUE THREAD

**Issue by popcorn** [kjvarga/sitemap_generator#370]
For various reasons, I may need to serve my sitemap from the Heroku app but without using S3 or any other 3rd party file hosting.

My idea was to have a cron job that runs `sitemap:refresh` or similar every day, gets the `sitemap.xml` as a string, store it in DB and then just server the sitemap from DB.

Is there any way to do this? I'm having trouble figuring out how to get out sitemap.xml as a Ruby string.

Btw, is there any reason why this is a terrible idea?

**Comment by jrochkind** [comment]
Maybe just write it to file system, then have your rake task read it from file system and put it into db?

**Comment by kjvarga** [comment]
What @jrochkind says is probably the easiest for you.  You could also define your own Adapter (see README).  It just needs a `def write(location, raw_data)` method and then you can direct the data to anywhere you like.

**Comment by unikitty37** [comment]
It looks like the Adapter `write` method *already* returns the sitemap, but I can't see how to get that to be returned from `SitemapGenerator::Sitemap.create`. Could you expand on how I could create a JustReturnAStringAdapter that will cause the XML to be returned as a string from `SitemapGenerator::Sitemap.create`?

OTOH, it already returns a `SitemapGenerator::LinkSet` — is there any chance of `SitemapGenerator::LinkSet` gaining a `to_xml` method? That way, I could add a NullAdapter that simply doesn't do anything in its `write` method…

Writing already-held data to a file and then reading it back in is rather wasteful if you just need the sitemap in a string.

Some background: my Rails app is purely backend, created with `rails new --api`. Rather than have the frontend request *all* the site data and then build the sitemap on the frontend in Node, I'd rather have an API endpoint which returns the sitemap, that can be called hourly by the frontend and cached there. Obviously, the gem was created before API-only Rails apps were really a thing, but it would be very useful in these cases to just be able to get the sitemap as a string using a built-in method…

**Comment by kjvarga** [comment]
You're far better off writing to S3 and refreshing on a schedule.  It's implicitly "cached" and there's no overhead for you writing controllers and managing caching.  That's why there aren't lots of solutions for that in Rails, it's just not a necessary pattern to implement.

Having a `to_xml` method on a LinkSet wouldn't make sense because there are multiple files encapsulated by that class (the index and sitemap files).

The adapter can be as simple as:
```ruby
class MyCustomAdapter
  def write(location, xml)
    // do whatever you want here.  See the location class for methods to access filename
  end
end
```

**Comment by kjvarga** [comment]
Typical sitemaps can contain hundreds of thousands of links.  If your sitemap is so small, just turn off the index, turn off compression, and you'll only have one "file" with your whole sitemap context.

**Comment by unikitty37** [comment]
The problem with S3 is that it costs money, and puts the data at the mercy of a third party. (The site's for a non-profit campaigning organisation, and since Amazon don't let you pay upfront so you can put a year's worth of credit up in one go, I'd have to submit an expense report on paper every month and end up with a cheque that has to be taken to the bank, as the organisation doesn't have online payment available.) I'd rather keep as much as I can in-house.

I already worked out the basics of the adapter, except for the fact that it has to write the data somewhere, either a file or a remote server — I wanted to simply get the XML in a Ruby variable that could be passed straight to `render`. But I guess that wouldn't work once the sitemap gets large enough to be split, in any case. 

What I ended up doing was having the backend write to a file and then render that (with a TODO for supporting multiple files once the site has grown more, since this is an MVP :) The frontend pulls it once an hour and stashes it in the appropriate place. 

Thanks!

```ruby
      def sitemap
        Dir.mktmpdir('sitemap', 'tmp') do |sitemap_folder|
          SitemapGenerator::Sitemap.create(public_path: sitemap_folder) do
            # add entries here
          end

          sitemap_file = "#{sitemap_folder}/sitemap.xml"
          if File.exist? sitemap_file
            render plain: IO.read(sitemap_file), content_type: 'application/xml'
          else
            render plain: "File not found", status: :internal_server_error
          end
        end
      end
```

**Comment by jrochkind** [comment]
> I already worked out the basics of the adapter, except for the fact that it has to write the data somewhere, either a file or a remote server 

Perhaps you could use a StringIO object to get it in-memory instead?  It ought not to be hard to write an adapter that receives the XML in a String in memory. 

As you say, the problem is that it does need to go *somewhere* for storage and delivery to crawlers. If you don't want to put it in S3, that's up to you, right?  You could put it in the database if you want, and don't mind putting a large BLOB in the database. Or, like... redis? It's really up to you. 

For most people, on heroku, where you don't have a persistent file system, they decide putting it in a key-value storage like S3 is the way to go. When your infrastructure is already heroku, I am not totally following the concern about being "at the mercy of a third party"  -- but you can put it wherever you want, for sure! That heroku does not provide a persistent file system is just part of heroku, nothing the gem can do about it!
