### ISSUE TITLE
Is it possible to add additional metadata fields to the xml

### ISSUE THREAD

**Issue by a85sharm** [kjvarga/sitemap_generator#412]
I have been using this gem for some time now, and just wanted to clarify that it isnt possible to add additional metadata to the sitemaps when using this gem right? I am implementing a new search and was hoping to just add in a few fields to my sitemap service but it seems like it isnt supported by this gem. Below is an example of what I am looking to do.
https://docs.coveo.com/en/2656/index-content/index-xml-sitemap-metadata

**Comment by kjvarga** [comment]
@a85sharm unfortunately it doesn't support it out of the box, but it's easy to add in a fork of the repo because it's just a couple of changes needed.  I could show you an example of that if you'd like.  Unfortunately you wouldn't get future updates to the gem, but not a lot is changing these days, and I think the parts that would be modified the changes would merge without conflicts.  But depends on your skill level

**Comment by a85sharm** [comment]
Hey @kjvarga thanks for the response, i had assumed as much, it would just be changes in the sitemap_url.rb right? and then just updating the gem version number?

**Comment by kjvarga** [comment]
No need to mess with the version number, since I don't think this will make it into the mainline.  Unless the solution were abstracted to make it easy to support any sitemap extension.

Here's the changes required and an example of the input https://github.com/kjvarga/sitemap_generator/pull/413

**Comment by a85sharm** [comment]
Hey this is working perfectly! I really appreciate the responses and the time you took to build me an example!

**Comment by kjvarga** [comment]
Awesome!  You’re welcome.  You caught me at a good time.
